//! End-to-end: what `install` scaffolds runs the runtime CLI inside the project,
//! the way a terminal agent runs it — `node {project-root}/_bmad/ade-runtime.mjs`
//! `<script> … …` — so the bundle under test is the one that ships, in
//! `resources/ade-runtime.mjs` (regenerated by `npm run build`, committed so the
//! test — and the crate itself, whose build maps the file as a bundled resource —
//! can read it).
//!
//! The tests sit in a `bmadv6_e2e` module so the plan's own command,
//! `cargo test bmadv6_e2e`, selects them: cargo's filter matches test names,
//! and a bare `#[test]` in this file would be filtered out.

use better_terminal_lib::bmadv6;
use std::path::{Path, PathBuf};

/// `node` must be present for these tests; skip otherwise (CI has it).
fn node_is_available() -> bool {
    std::process::Command::new("node").arg("--version").output().is_ok()
}

/// A pid-named temp dir, emptied first: a leftover from a crashed run would
/// otherwise satisfy the assertions without exercising the scaffold's writes.
fn temp(name: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!("{name}-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).unwrap();
    dir
}

/// The scaffolded runtime, invoked as the patched skills' call sites invoke it.
fn runtime(dir: &Path, args: &[&str]) -> std::process::Output {
    std::process::Command::new("node")
        .arg(dir.join("_bmad/ade-runtime.mjs"))
        .args(args)
        .output()
        .unwrap()
}

fn stdout(out: &std::process::Output) -> String {
    String::from_utf8_lossy(&out.stdout).into_owned()
}

/// A recursive copy — std has none — for composing the packaged resource root.
fn copy_dir(from: &Path, to: &Path) {
    std::fs::create_dir_all(to).unwrap();
    for entry in std::fs::read_dir(from).unwrap() {
        let entry = entry.unwrap();
        let target = to.join(entry.file_name());
        if entry.file_type().unwrap().is_dir() {
            copy_dir(&entry.path(), &target);
        } else {
            std::fs::copy(entry.path(), &target).unwrap();
        }
    }
}

/// The resource root as the packaging builds it: the vendored tree with the
/// bundle at its top level, which is what tauri.conf.json's
/// `"resources/ade-runtime.mjs": "resources/bmad-v6/ade-runtime.mjs"` mapping
/// produces. In the source tree the bundle sits one level up, in `resources/`.
fn packaged_resource_root(into: &Path) -> PathBuf {
    let resources = Path::new(env!("CARGO_MANIFEST_DIR")).join("resources");
    copy_dir(&resources.join("bmad-v6"), into);
    std::fs::copy(resources.join("ade-runtime.mjs"), into.join("ade-runtime.mjs")).unwrap();
    into.to_path_buf()
}

#[cfg(test)]
mod bmadv6_e2e {
    use super::*;

    #[test]
    fn scaffolded_project_runs_the_runtime_cli() {
        let dir = std::env::temp_dir().join(format!("bmadv6-e2e-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let src = std::env::temp_dir().join(format!("bmadv6-e2e-src-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&src);
        std::fs::create_dir_all(src.join("skills")).unwrap();
        std::fs::copy(concat!(env!("CARGO_MANIFEST_DIR"), "/resources/ade-runtime.mjs"), src.join("ade-runtime.mjs")).unwrap();

        let mut report = bmadv6::ScaffoldReport::default();
        bmadv6::install(&src, &dir, &mut report).unwrap();

        // `node` must be present for this test; skip otherwise (CI has it).
        if std::process::Command::new("node").arg("--version").output().is_err() { return; }
        let out = std::process::Command::new("node")
            .arg(dir.join("_bmad/ade-runtime.mjs"))
            .arg("resolve_config").arg("--project-root").arg(&dir)
            .output().unwrap();
        assert!(out.status.success());
        let stdout = String::from_utf8_lossy(&out.stdout);
        assert!(stdout.contains("output_folder"), "runtime returned: {stdout}");
        // The runtime's answer is the scaffolded project's, not a canned one.
        // JSON escapes a Windows path's separators, hence the unescape.
        let unescaped = stdout.replace("\\\\", "\\");
        assert!(
            unescaped.contains(&dir.to_string_lossy().into_owned()),
            "runtime did not answer from this project: {stdout}"
        );
        std::fs::remove_dir_all(&dir).ok();
        std::fs::remove_dir_all(&src).ok();
    }

    /// The end-to-end chain with the shipped resources rather than a fixture: the
    /// vendored tree and the committed bundle compose into the resource root the
    /// packaging builds from them, that root scaffolds, and a second runtime
    /// command — the patched skills' `tickets` call site — answers against the
    /// scaffolded project.
    #[test]
    fn the_bundled_resources_scaffold_a_project_the_runtime_serves() {
        if !node_is_available() {
            return;
        }
        let resources = packaged_resource_root(&temp("bmadv6-e2e-resources"));
        let dir = temp("bmadv6-e2e-bundle");
        let mut report = bmadv6::ScaffoldReport::default();
        bmadv6::install(&resources, &dir, &mut report).unwrap();

        assert!(dir.join(".claude/skills/bmad/SKILL.md").is_file(), "the vendored skills scaffold");
        assert_eq!(std::fs::read_to_string(dir.join(".ade/methodology")).unwrap().trim(), "v6");

        // `tickets next` on a store with nothing in it: the ticket tree's commands
        // are routed by tickets.ts, so an answer here means the bundle dispatched.
        let store = dir.join("_bmad-output/backlog");
        std::fs::create_dir_all(&store).unwrap();
        let root = dir.to_string_lossy().into_owned();
        let out = runtime(
            &dir,
            &["tickets", "next", &store.to_string_lossy(), "--project-root", &root],
        );
        let text = stdout(&out);
        assert!(
            out.status.success(),
            "tickets next failed: {text}{}",
            String::from_utf8_lossy(&out.stderr)
        );
        assert!(text.contains("\"folder\": \"backlog\""), "tickets next returned: {text}");
        assert!(text.contains("\"store\": \"repo\""), "tickets next returned: {text}");

        std::fs::remove_dir_all(&dir).ok();
        std::fs::remove_dir_all(&resources).ok();
    }
}
